// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crjratdtrrhucfumdubq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyanJhdGR0cnJodWNmdW1kdWJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTI5OTEsImV4cCI6MjA3MzI2ODk5MX0.Q6jTWtabWrc2sxF4704wXO4E4KRfIkn1mhosVhgdcXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});